# Site Info
title: 'Fractal logs'
tagline: 'Fractal logs'
description: '어디로 튈지 모르는 공부 로그'
baseurl: ""
url: https://karlbishnu.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Ryoo Myung-han
  description: 구현자
  contact:
    linkedin:  https://www.linkedin.com/in/myunghanryoo-23b57682/
    github:    https://github.com/karlbishnu
    facebook:  https://www.facebook.com/karlbishnu
    email:    mailto:karlbishnu@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    - { Algorithm: '/blog/categories/#Algorithm' }
    - { Project: '/blog/categories/#project' }
    - { Jekyll: '/blog/categories/#Jekyll' }
    - { etc: '/blog/categories/#etc' }
  Tags:
    - '/blog/tags/'
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-133907493-1' # leave blank if you don't want google analytics
disqus_short_name: 'karlbishnu-github-io' # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate
